@startuml Class diagram

class User {
  +String id
  +String username
  +String walletAddress
}

class Token {
  +String id
  +String symbol
}

class Meme {
  +String id
  +String tokenId
  +String name
  +Int hp
  +Int attack
  +Int defense
  +Int criticChance
  +Int speed
}

class UserToken {
  +String id
  +String userId
  +String tokenId
  +bigint balance
}

class UserrMeme {
  +String id
  +String userId
  +String memeId
}

class Skills {
  +String id
  +String skillTypeId
  +String name
  +Int power 
}

class SkillTypes {
  +String id
  +String name
}

class MemeSkills {
  +String id
  +String memeId
  +String skillId
}

class AttackResultId {
  +String id
  +String name
}


class BattleSession {
  +String id
  +Date createdAt
  +String status
}

class BattleSessionUser {
  +String id
  +String battleSessionid
  +String userId
}

class BattleSessionUserMeme {
   +String id
  +String battleSessionid
  +String userMemeId
}

class BattleSessionAttacksLog {
  +String id
  +Date timestamp
  +String atackerId
  +String receiverId
  +String skillid
  +string  attackResultId
}

class MemeStakingLine {
  +String id
  +Float stakedAmount
  +Date createdAt
}

class MemeWithdrawLine {
  +String id
  +Float withdrawAmount
  +Date createdAt
}

    User "1" -- "*" UserToken : has
    User "1" -- "*" UserMeme : owns
    User "1" -- "*" BattleSessionUser : participates
    Token "1" -- "*" UserToken : represents
    Meme "1" -- "*" UserMeme : instance of
    Meme "1" -- "*" MemeSkills : has
    Skills "1" -- "*" MemeSkills : associated with
    SkillTypes "1" -- "*" Skills : categorizes
    BattleSession "1" -- "*" BattleSessionUser : includes
    BattleSession "1" -- "*" BattleSessionUserMeme : involves
    BattleSession "1" -- "*" BattleSessionAttacksLog : records
    AttackResultId "1" -- "*" BattleSessionAttacksLog : describes
    Meme "1" -- "*" MemeStakingLine : stakes
    Meme "1" -- "*" MemeWithdrawLine : withdraws
