version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: memearena-db
    environment:
      POSTGRES_USER: magaiba
      POSTGRES_PASSWORD: magaiba
      POSTGRES_DB: meme-arena
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
