import "./globals.css";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import AppWalletProvider from "../context/AppWalletProvider";

const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={` ${montserrat.className} font-montserrat`}>
      <body className="min-h-screen p-2 flex flex-col">
        <AppWalletProvider>{children}</AppWalletProvider>
      </body>
    </html>
  );
}
